version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install -r ./LF1/requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip ./LF1/lambda_function.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name index-photo-v2 --zip-file fileb://deployment_package.zip
      - echo "DONE!!"

  # post_build:
  #   commands:
  #     - sam package --output-template-file template.yml --s3-bucket codepipeline-us-east-1-891057533035

  # post_build:
  #   commands:
  #     - aws cloudformation package --template .aws-sam/build/template.yaml --kms-key-id arn:aws:kms:us-east-1:979351636556:alias/aws/s3 --s3-bucket codepipeline-us-east-1-891057533035 --output-template template.yml

# artifacts:
#   # files:
#   #   - '**/*'
#   type: zip
#   files:
#     - template.yml